version: "3"

services:
  client:
    image: "cygnetops/multi-client-10-14"
    mem_limit: 128mb
    hostname: client
  server:
    image: "cygnetops/multi-client-10-14"
    mem_limit: 128mb
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=5432
    worker:
      image: "cygnetops/multi-worker-10-14"
      mem_limit: 128m
      hostname: worker
      environment:
        - REDIS_HOST=$REDIS_HOST
        - REDIS_PORT=$REDIS_PORT
    nginx:
      image: "cygnetops/multi-nginx-10-14"
      mem_limit: 128m
      hostname: nginx
      ports:
        - "80:80"

